### ISSUE TITLE
fat-dash fixed the old error?

### ISSUE THREAD

**Issue by RafaRed** [sidtheone/fat-dash-fix#2]
I had to go back, leaving the stats as they were before. Because the replacement has stopped working, I believe the fat-dash has been updated to the format xx:xx:xx.xxx

in case you need to come back too, just change the content_new for this one:
content_new = re.sub('(..:..:..)(:)(..)',r'\1.\3', content, flags = re.M)

BACKUP FIRST.

**Comment by sidtheone** [comment]
Created unfix script with above changes.
